
package myfitdayapp;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.border.Border;




/**
 * frame for adding new consumption entries
 * name, calories and macros
 * 
 * @author olgachristensen
 */
public class AddFood extends javax.swing.JFrame {

    private DBHandler dbh;
    /**
     * Creates new form AddFood
     * @throws java.lang.Exception
     */
    public AddFood() throws Exception {
        initComponents();
        dbh = new DBHandler();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lName = new javax.swing.JLabel();
        lCal = new javax.swing.JLabel();
        lFat = new javax.swing.JLabel();
        lCarbs = new javax.swing.JLabel();
        lProtein = new javax.swing.JLabel();
        fName = new javax.swing.JTextField();
        fCal = new javax.swing.JTextField();
        fFat = new javax.swing.JTextField();
        fCarbs = new javax.swing.JTextField();
        fProtein = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        errorMsg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        lName.setText("Name:");

        lCal.setText("Calories:");

        lFat.setText("Fat:");

        lCarbs.setText("Carbs:");

        lProtein.setText("Protein:");

        fCal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fCalActionPerformed(evt);
            }
        });

        fFat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fFatActionPerformed(evt);
            }
        });

        fCarbs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fCarbsActionPerformed(evt);
            }
        });

        fProtein.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fProteinActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        errorMsg.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(errorMsg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lName)
                                    .addComponent(lCal)
                                    .addComponent(lFat)
                                    .addComponent(lCarbs)
                                    .addComponent(lProtein))
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fName, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fCal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fFat, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fCarbs, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fProtein, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(214, Short.MAX_VALUE)
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel)))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lName)
                    .addComponent(fName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCal)
                    .addComponent(fCal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fFat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lFat))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fCarbs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lCarbs))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fProtein, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lProtein))
                .addGap(18, 18, 18)
                .addComponent(errorMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnCancel))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fCalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fCalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fCalActionPerformed

    private void fFatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fFatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fFatActionPerformed

    private void fCarbsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fCarbsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fCarbsActionPerformed

    private void fProteinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fProteinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fProteinActionPerformed

    // if clicked CANCEL - close the frame 
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        super.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    // if clicked ADD - insert data in DB and close the frame 
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        
        Border border = BorderFactory.createLineBorder(Color.RED, 1);
        
        try {
            
            int cal = Integer.parseInt(fCal.getText());
            int fat = Integer.parseInt(fFat.getText());
            int carb = Integer.parseInt(fCarbs.getText());
            int p = Integer.parseInt(fProtein.getText());

            dbh.insertDataFood(dbh.getDate(), fName.getText(), cal, fat, carb, p);
            
            
            
            super.dispose();
        
        } catch (NumberFormatException e) {
            errorMsg.setText("Only integers");
            
            try {
                int cal = Integer.parseInt(fCal.getText());
            } catch (NumberFormatException ex) {
                fCal.setBorder(border);
            }
            
            try {
                int f = Integer.parseInt(fFat.getText());
            } catch (NumberFormatException ex) {
                fFat.setBorder(border);
            }
            
            try {
                int carb = Integer.parseInt(fCarbs.getText());
            } catch (NumberFormatException ex) {
                fCarbs.setBorder(border);
            }
            
            try {
                int p = Integer.parseInt(fProtein.getText());
            } catch (NumberFormatException ex) {
                fProtein.setBorder(border);
            }
            
        }
        
        
    
        //dbh.printAllFood();
        
    }//GEN-LAST:event_btnAddActionPerformed

    // REMOVE main???
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
        });
        
        
        
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JLabel errorMsg;
    private javax.swing.JTextField fCal;
    private javax.swing.JTextField fCarbs;
    private javax.swing.JTextField fFat;
    private javax.swing.JTextField fName;
    private javax.swing.JTextField fProtein;
    private javax.swing.JLabel lCal;
    private javax.swing.JLabel lCarbs;
    private javax.swing.JLabel lFat;
    private javax.swing.JLabel lName;
    private javax.swing.JLabel lProtein;
    // End of variables declaration//GEN-END:variables
}
