
package myfitdayapp;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 * Dialog window for handling records of food consumption for one day
 * User can 
 * - view the records (in table form)
 * - edit existing records
 * - delete existing records
 * - add new records
 * 
 * @author olgachristensen
 */
public class EditFood extends javax.swing.JDialog {

    private DBHandler dbh;
    private ResultSet rs;
    public String date;
    private int selectedRow;
    private DefaultTableModel dtm;
    public int err;
    
    /**
     * Constructor
     * Creates new form EditFood
     */
    public EditFood(String d, JFrame parent, boolean modal) {
        super(parent, modal);
        
        dbh = new DBHandler();
        rs = dbh.getFoodTable(d);
        date = d;
        selectedRow = 0;
        
        // remove close / minimize controls
        setUndecorated(true);
        initComponents();
        showDateLable.setText(d);
        setColWidth();
        
    }
    
    private void setColWidth() {
        foodTable.getColumnModel().getColumn(0).setPreferredWidth(120);
        foodTable.getColumnModel().getColumn(1).setPreferredWidth(40);
        foodTable.getColumnModel().getColumn(2).setPreferredWidth(40);
        foodTable.getColumnModel().getColumn(3).setPreferredWidth(40);
        foodTable.getColumnModel().getColumn(4).setPreferredWidth(40);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        foodTable = new javax.swing.JTable(buildTable(rs)) {
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };
        btnClose = new javax.swing.JButton();
        nameLable = new javax.swing.JLabel();
        calLable = new javax.swing.JLabel();
        fatLable = new javax.swing.JLabel();
        carbLable = new javax.swing.JLabel();
        proteinLable = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        calField = new javax.swing.JTextField();
        fatField = new javax.swing.JTextField();
        carbField = new javax.swing.JTextField();
        proteinField = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        dateLable = new javax.swing.JLabel();
        showDateLable = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setPreferredSize(new java.awt.Dimension(600, 408));
        setResizable(false);

        foodTable.setSelectionBackground(new java.awt.Color(153, 153, 153));
        foodTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        foodTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                foodTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(foodTable);

        btnClose.setText("Close");
        btnClose.setMaximumSize(new java.awt.Dimension(80, 29));
        btnClose.setMinimumSize(new java.awt.Dimension(80, 29));
        btnClose.setPreferredSize(new java.awt.Dimension(80, 29));
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        nameLable.setText("Name:");

        calLable.setText("Calories:");

        fatLable.setText("Fat:");

        carbLable.setText("Carbs:");

        proteinLable.setText("Protein:");

        nameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameFieldKeyTyped(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.setEnabled(false);
        btnUpdate.setMaximumSize(new java.awt.Dimension(90, 29));
        btnUpdate.setMinimumSize(new java.awt.Dimension(90, 29));
        btnUpdate.setPreferredSize(new java.awt.Dimension(90, 29));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.setEnabled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        dateLable.setText("Date:");

        showDateLable.setText("today");

        btnAdd.setText("Add");
        btnAdd.setEnabled(false);
        btnAdd.setMaximumSize(new java.awt.Dimension(90, 29));
        btnAdd.setMinimumSize(new java.awt.Dimension(90, 29));
        btnAdd.setPreferredSize(new java.awt.Dimension(90, 29));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("MEALS LOG");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/food.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameLable)
                                    .addComponent(calLable)
                                    .addComponent(fatLable)
                                    .addComponent(carbLable)
                                    .addComponent(proteinLable)
                                    .addComponent(dateLable))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(showDateLable)
                                    .addComponent(proteinField, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(carbField, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(fatField, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(calField, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(nameField, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 7, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(17, 17, 17))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateLable)
                            .addComponent(showDateLable))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLable)
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(calLable)
                            .addComponent(calField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fatLable)
                            .addComponent(fatField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(carbLable)
                            .addComponent(carbField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(proteinLable)
                            .addComponent(proteinField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelete)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // clicked CLOSE
    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    // clicked DELETE
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // show confirmation dialog
        int q = JOptionPane.showConfirmDialog(this, "Delete chosen record?", 
                "Delete", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE);
        
        // if deletion confirmed
        if (q == 0) {
            // remove record from the table
            dtm.removeRow(selectedRow);
            // update DB
            dbh.updateFoodDelete(date, selectedRow);
            
            emptyTextBoxes();
            removeBorder();
            disableButtons();
        }
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    // a row in the table was clicked
    private void foodTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foodTableMouseClicked
        
        enableButtons();
        removeBorder();
        
        // get index of selected row
        selectedRow = foodTable.getSelectedRow();

        // fill the text boxes accordingly 
        
        String n = foodTable.getModel().getValueAt(selectedRow, 0).toString();
        nameField.setText(n);
            
        String cal = foodTable.getModel().getValueAt(selectedRow, 1).toString();
        calField.setText(cal);
        
        String f = foodTable.getModel().getValueAt(selectedRow, 2).toString();
        fatField.setText(f);
        
        String c = foodTable.getModel().getValueAt(selectedRow, 3).toString();
        carbField.setText(c);
        
        String p = foodTable.getModel().getValueAt(selectedRow,4).toString();
        proteinField.setText(p);
            
    }//GEN-LAST:event_foodTableMouseClicked

    // clicked UPDATE
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // prepare red border for text boxes with incompatible input
        Border border = BorderFactory.createLineBorder(Color.RED, 1);
        removeBorder();
        
        
        try {
            // check if Name field is not empty
            if (nameField.getText().length() != 0 ) {
                // update table
                foodTable.setValueAt(nameField.getText(), selectedRow, 0);
                foodTable.setValueAt(calField.getText(), selectedRow, 1);
                foodTable.setValueAt(fatField.getText(), selectedRow, 2);
                foodTable.setValueAt(carbField.getText(), selectedRow, 3);
                foodTable.setValueAt(proteinField.getText(), selectedRow, 4);

                String[] data = {nameField.getText(), calField.getText(), fatField.getText(), carbField.getText(), proteinField.getText()};

                // update DB
                dbh.updateFoodEdit(date, selectedRow, data);

                emptyTextBoxes();
                disableButtons();
            }
            else
                nameField.setBorder(border);
        
        }
        catch (NumberFormatException e) {
            // put red border on text fields with bad input
            try {
                int cal = Integer.parseInt(calField.getText());
            } catch (NumberFormatException ex) {
                calField.setBorder(border);
            }
            
            try {
                int f = Integer.parseInt(fatField.getText());
            } catch (NumberFormatException ex) {
                fatField.setBorder(border);
            }
            
            try {
                int carb = Integer.parseInt(carbField.getText());
            } catch (NumberFormatException ex) {
                carbField.setBorder(border);
            }
            
            try {
                int p = Integer.parseInt(proteinField.getText());
            } catch (NumberFormatException ex) {
                proteinField.setBorder(border);
            }
        }
        
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    // enables ADD button when something is typed in the name field
    private void nameFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameFieldKeyTyped
        btnAdd.setEnabled(true);
        
        // limits the text input to 20 chars
        if (nameField.getText().length() >= 20)
            evt.consume();
    }//GEN-LAST:event_nameFieldKeyTyped

    // clicked ADD
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // prepare red border for text boxes with incompatible input
        Border border = BorderFactory.createLineBorder(Color.RED, 1);
        removeBorder();
        
        try {
            // check if Name field is not empty
            if (nameField.getText().length() != 0) {
                Vector<Object> data = new Vector<Object>();
                
                int cal = Integer.parseInt(calField.getText());
                int fat = Integer.parseInt(fatField.getText());
                int carb = Integer.parseInt(carbField.getText());
                int p = Integer.parseInt(proteinField.getText());
                
                data.add(nameField.getText());
                data.add(cal);
                data.add(fat);
                data.add(carb);
                data.add(p);

                // update table
                dtm.addRow(data);
                // insert record in DB
                dbh.insertDataFood(date, nameField.getText(), cal, fat, carb, p);

                emptyTextBoxes();
                disableButtons();
            }
            else {
                nameField.setBorder(border);
                
            }
        
        } catch (NumberFormatException e) {
            //handle bad input
            
            try {
                int cal = Integer.parseInt(calField.getText());
            } catch (NumberFormatException ex) {
                calField.setBorder(border);
            }
            
            try {
                int f = Integer.parseInt(fatField.getText());
            } catch (NumberFormatException ex) {
                fatField.setBorder(border);
            }
            
            try {
                int carb = Integer.parseInt(carbField.getText());
            } catch (NumberFormatException ex) {
                carbField.setBorder(border);
            }
            
            try {
                int p = Integer.parseInt(proteinField.getText());
            } catch (NumberFormatException ex) {
                proteinField.setBorder(border);
            }
            
        }
        
    }//GEN-LAST:event_btnAddActionPerformed

    // empties the text boxes
    private void emptyTextBoxes() {
        nameField.setText("");
        calField.setText("");
        fatField.setText("");
        carbField.setText("");
        proteinField.setText("");
    }
    
    // removes red border from text fields (if any)
    private void removeBorder() {
        nameField.setBorder(null);
        calField.setBorder(null);
        fatField.setBorder(null);
        carbField.setBorder(null);
        proteinField.setBorder(null);
    }
    
    // disables the buttons    
    // Add, Delete, Update
    private void disableButtons() {
        btnAdd.setEnabled(false);
        btnDelete.setEnabled(false);
        btnUpdate.setEnabled(false);
    }
    
    // enables the buttons    
    // Add, Delete, Update
    private void enableButtons() {
        btnAdd.setEnabled(true);
        btnDelete.setEnabled(true);
        btnUpdate.setEnabled(true);
    }
    
    // builds the table with daily records
    public DefaultTableModel buildTable(ResultSet rs)  {
        // column names
        Vector<String> columnNames = new Vector<String>();
        
        columnNames.add("Name");
        columnNames.add("Cal");
        columnNames.add("F");
        columnNames.add("C");
        columnNames.add("P");
        
        // records to fill in
        Vector<Vector<Object>> data = new Vector<Vector<Object>>();
        
        try {
            ResultSetMetaData metaData = rs.getMetaData();
            int columns = metaData.getColumnCount();

            // get data for the table
            while (rs.next()) {
                Vector<Object> vector = new Vector<Object>();
                for (int i = 1; i <= columns; i++) {
                    vector.add(rs.getObject(i));
                }
                data.add(vector);
            }
        } catch (SQLException ex) {
            Logger.getLogger(DBHandler.class.getName()).log(Level.SEVERE, null, ex);
        } 

        dtm = new DefaultTableModel(data, columnNames);
        
        return dtm;

    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JTextField calField;
    private javax.swing.JLabel calLable;
    private javax.swing.JTextField carbField;
    private javax.swing.JLabel carbLable;
    private javax.swing.JLabel dateLable;
    private javax.swing.JTextField fatField;
    private javax.swing.JLabel fatLable;
    private javax.swing.JTable foodTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLable;
    private javax.swing.JTextField proteinField;
    private javax.swing.JLabel proteinLable;
    private javax.swing.JLabel showDateLable;
    // End of variables declaration//GEN-END:variables
}
