/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myfitdayapp;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Vector;


/**
 *
 * @author olgachristensen
 */
public class MainFrame extends javax.swing.JFrame {

    private DBHandler dbh;
    //private Vector<Vector<String>> food;
    private Vector<String> header;
    private String food;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        //tableFood.getColumnModel().getColumn(1).setPreferredWidth(100);
        //tableSport.getColumnModel().getColumn(1).setPreferredWidth(100);
        resDate.setText(getDate());
        
        
        dbh = new DBHandler();
        header = new Vector<String>();
        header.add("name");
        header.add("n");
        
        try {
            food = dbh.getTodayFood(getDate());
            textFood.setText(food);
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtGoal = new javax.swing.JLabel();
        txtToGo = new javax.swing.JLabel();
        txtTotal = new javax.swing.JLabel();
        txtConsumed = new javax.swing.JLabel();
        txtSpent = new javax.swing.JLabel();
        resGoal = new javax.swing.JLabel();
        resTotal = new javax.swing.JLabel();
        resConsumed = new javax.swing.JLabel();
        resSpent = new javax.swing.JLabel();
        resToGo = new javax.swing.JLabel();
        txtDate = new javax.swing.JLabel();
        resDate = new javax.swing.JLabel();
        lableFood = new javax.swing.JLabel();
        lableSport = new javax.swing.JLabel();
        addFood = new javax.swing.JButton();
        addSport = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        textFood = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(230, 230, 230));

        lPanel.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 193, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 161, Short.MAX_VALUE)
        );

        txtGoal.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        txtGoal.setForeground(new java.awt.Color(255, 255, 255));
        txtGoal.setText("Goal:");

        txtToGo.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        txtToGo.setForeground(new java.awt.Color(255, 255, 255));
        txtToGo.setText("To go:");

        txtTotal.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(255, 255, 255));
        txtTotal.setText("Total:");

        txtConsumed.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        txtConsumed.setForeground(new java.awt.Color(255, 255, 255));
        txtConsumed.setText("Consumed:");

        txtSpent.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        txtSpent.setForeground(new java.awt.Color(255, 255, 255));
        txtSpent.setText("Spent:");

        resGoal.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        resGoal.setForeground(new java.awt.Color(255, 153, 0));
        resGoal.setText("2000");

        resTotal.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        resTotal.setForeground(new java.awt.Color(255, 153, 0));
        resTotal.setText("2000");

        resConsumed.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        resConsumed.setForeground(new java.awt.Color(255, 153, 0));
        resConsumed.setText("2000");

        resSpent.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        resSpent.setForeground(new java.awt.Color(255, 153, 0));
        resSpent.setText("2000");

        resToGo.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        resToGo.setForeground(new java.awt.Color(255, 153, 0));
        resToGo.setText("2000");

        javax.swing.GroupLayout lPanelLayout = new javax.swing.GroupLayout(lPanel);
        lPanel.setLayout(lPanelLayout);
        lPanelLayout.setHorizontalGroup(
            lPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(lPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(lPanelLayout.createSequentialGroup()
                        .addComponent(txtToGo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resToGo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(lPanelLayout.createSequentialGroup()
                        .addComponent(txtGoal, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resGoal, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lPanelLayout.createSequentialGroup()
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lPanelLayout.createSequentialGroup()
                        .addComponent(txtConsumed)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resConsumed, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lPanelLayout.createSequentialGroup()
                        .addComponent(txtSpent, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resSpent, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        lPanelLayout.setVerticalGroup(
            lPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(lPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtGoal)
                    .addComponent(resGoal, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(lPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lPanelLayout.createSequentialGroup()
                        .addComponent(resTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(resConsumed)
                        .addGap(12, 12, 12)
                        .addComponent(resSpent))
                    .addGroup(lPanelLayout.createSequentialGroup()
                        .addComponent(txtTotal)
                        .addGap(18, 18, 18)
                        .addComponent(txtConsumed)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSpent)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addGroup(lPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtToGo)
                    .addComponent(resToGo))
                .addGap(14, 14, 14))
        );

        txtDate.setText("Date:");

        resDate.setText("5 May 2016");

        lableFood.setText("FOOD");

        lableSport.setText("SPORT");

        addFood.setText("+");
        addFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFoodActionPerformed(evt);
            }
        });

        addSport.setText("+");

        textFood.setColumns(20);
        textFood.setRows(5);
        jScrollPane3.setViewportView(textFood);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtDate)
                        .addGap(39, 39, 39)
                        .addComponent(resDate))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lableFood)
                        .addGap(27, 27, 27)
                        .addComponent(addFood, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(280, 280, 280)
                        .addComponent(lableSport)
                        .addGap(18, 18, 18)
                        .addComponent(addSport, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(580, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDate)
                    .addComponent(resDate))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lableFood)
                    .addComponent(addFood)
                    .addComponent(lableSport)
                    .addComponent(addSport))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String getDate() {
        Calendar calendar = new GregorianCalendar();
        int month = calendar.get(Calendar.MONTH);
        int year = calendar.get(Calendar.YEAR);
        int day = calendar.get(Calendar.DAY_OF_MONTH);
        
        String date = "";
        //date += day +"."+(month+1)+"."+ year;
        date += year + "-" + (month+1) + "-" + day;
        
        
        return date;
        
    }
    
    
    private void addFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFoodActionPerformed
        AddFood af;
        try {
            af = new AddFood();
            af.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_addFoodActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFood;
    private javax.swing.JButton addSport;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel lPanel;
    private javax.swing.JLabel lableFood;
    private javax.swing.JLabel lableSport;
    private javax.swing.JLabel resConsumed;
    private javax.swing.JLabel resDate;
    private javax.swing.JLabel resGoal;
    private javax.swing.JLabel resSpent;
    private javax.swing.JLabel resToGo;
    private javax.swing.JLabel resTotal;
    private javax.swing.JTextArea textFood;
    private javax.swing.JLabel txtConsumed;
    private javax.swing.JLabel txtDate;
    private javax.swing.JLabel txtGoal;
    private javax.swing.JLabel txtSpent;
    private javax.swing.JLabel txtToGo;
    private javax.swing.JLabel txtTotal;
    // End of variables declaration//GEN-END:variables
}
