/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myfitdayapp;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author olgachristensen
 */
public class StatusBar extends javax.swing.JComponent {

    private int goal;
    private int total;
    private int width;
    private int width1;
    private int width2;
    
    /**
     * Creates new form StatusBar
     */
    public StatusBar(int g, int t) {
        initComponents();
        
        setPreferredSize(new Dimension(286, 50));
        
        goal = g;
        total = t;
        width = 286;
        width1 = 0;
        width2 = 0;
        
    }
    
    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D box = (Graphics2D) g;

        
        if (goal - total > 0) {
            
            System.out.println("Positive");
            getWidthPositive();
            
            // green
            box.setColor(new Color(58, 222, 69));
            box.drawRect(0, 0, width1, 50);
            
            // light grey
            box.setColor(new Color(212, 212, 212));
            box.drawRect(width1, 0, width1 + width2, 50);
            
            
            
        } else {
            System.out.println("Negative");
            
            getWidthNegative();
            // green
            box.setColor(new Color(58, 222, 69));
            box.drawRect(0, 0, width1, 50);
            
            // red
            box.setColor(new Color(245, 56, 56));
            box.drawRect(width1, 0, width1 + width2, 50);
            
            
        }
        
    }
    
    private void getWidthPositive() {
        float x = width * total / goal;
        width1 = (int) x;
        width2 = width - width1;
    }
    
    
    private void getWidthNegative() {
        float x = width * (total / goal - 1);
        width1 = (int) x;
        width2 = width - width1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(300, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
